name: unofficial_filman_client
description: "This app allows you to browse, search, and watch movies and TV shows available on filman.cc."
publish_to: "none"
version: 1.3.3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  background_downloader: ^8.5.2
  collection: ^1.18.0
  dio: ^5.4.2+1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  html: ^0.15.4
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  open_file: ^3.3.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  version: ^3.0.2
  wakelock_plus: ^1.2.5
  webview_flutter: ^4.8.0
  screen_brightness: ^0.2.2+1
  flutter_cast_framework:
    git: https://github.com/Unofficial-Filman-Client/flutter_cast_framework
  fast_cached_network_image: ^1.2.9
  dio_cache_interceptor: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dart_code_metrics_presets: ^2.15.0

flutter:
  uses-material-design: true
